Deploy
volnistii11/accumulative-loyalty-system pull request #1
Opened 2023-07-25 21:32 UTC by volnistii11

2023-08-30 21:51 UTC, valentinsoe requested changes
Спасибо за работу

Хорошо, что есть отдельные уровни хендлеров, сервисов и бд. Плохо, что бизнес-логика почему-то существенной частью оказалась на уровне хендлеров.

Чего не хватает?
Не хватает тестов, местами транзакций, многопоточных обращений к внешнему сервису и корректной реакции на все его ответы(код 429).

2023-08-30 21:51 UTC, valentinsoe commented on cmd/gophermart/main.go
> +	err = database.RunMigrations(cfg.GetStorageDSN())
Почему бы здесь не использовать уже открытый connection?

2023-08-30 21:51 UTC, valentinsoe commented on cmd/gophermart/main.go
> +
Стоит добавить логику gracefull shutdown

2023-08-30 21:51 UTC, valentinsoe commented on internal/app/gophermart/api/accumulation.go
> +		defer r.Body.Close()
Закрывать тело запроса "руками" необязательно, http сервер делает это за нас.
Обязательно закрывать тело ответа, когда используется http клиент.

2023-08-30 21:51 UTC, valentinsoe commented on internal/app/gophermart/api/accumulation.go
> +		orderNumber, err = strconv.Atoi(string(body))
Номер заказа - не число. Номер заказа - строка состоящая из цифр. Она вполне может не влазить в стандартные типы.

2023-08-30 21:51 UTC, valentinsoe commented on internal/app/gophermart/api/accumulation.go
> +		accumulation.UserID = r.Context().Value(model.ContextKeyUserID).(int)
Лучше написать вспомогательную функцию для этого. Будет аккуратнее читаться.

2023-08-30 21:51 UTC, valentinsoe commented on internal/app/gophermart/api/accumulation.go
> +		err = a.accumulationService.AddOrder(&accumulation, storage)
Так как предыдущие проверки выполнены не в рамках транзакции, то здесь мы вполне можем получить ошибку уникальности orderId и вернуть пользователю 500, вмечто 200/409

2023-08-30 21:51 UTC, valentinsoe commented on internal/app/gophermart/api/accumulation.go
> +		if a.accumulationService.OrderExistsAndDoesNotBelongToTheUser(&accumulation, storage) {
Два запроса к БД для выполнения этих проверок - избыточно.

2023-08-30 21:51 UTC, valentinsoe commented on internal/app/gophermart/api/accumulation.go
> +		w.Header().Add("content-type", "application/json")
Занудство. Лучше унести это вниз фукнции. Чтобы во всех хендлерах это было одинаково(между logger.info и w.writeheade)

2023-08-30 21:51 UTC, valentinsoe commented on internal/app/gophermart/api/accumulation.go
> +		err := a.accumulationService.Withdraw(userID, &withdraw, storage)
Проверка баланса и списание делается в двух разных транзакциях. Значит можно увести баланс в минус.

2023-08-30 21:51 UTC, valentinsoe commented on internal/app/gophermart/api/auth.go
> +		jwtToken, err := a.authService.AuthenticateUser(&user, storage)
У нас уже есть все данные, чтобы создать токен, зачем лишнее обращение к БД?

2023-08-30 21:51 UTC, valentinsoe commented on internal/app/gophermart/client/accrual.go
> +			for _, newOrder := range newOrders {
Однопоточная обработка запросов во внешний сервис - имеет очень низкую пропускную способность. Запросы надо делать параллельно.

2023-08-30 21:51 UTC, valentinsoe commented on internal/app/gophermart/middleware/auth/auth.go
> +			ctx := context.WithValue(r.Context(), model.ContextKeyUserID, userID)
Очень странно, что эта константа(ContextKeyUserID) лежит в пакете моделей.

2023-08-30 21:51 UTC, valentinsoe commented on internal/app/gophermart/client/accrual.go
> +					logger.Error("", sl.Err(err))
Ошибки 204 и 429 нельзя так просто игнорировать, должна быть логика их обработки. Как минимум 429.

2023-08-30 21:51 UTC, valentinsoe commented on internal/app/gophermart/service/accumulation.go
Вот на этом уровне стоит быть всей бизнес-логике, а не на уровне хендлеров.
Задача хендлеров - распарсить запрос и сформировать ответ. Логика принятия решений как раз должна переехать сюда.
Иначе непонятен смысл наличия этого уровня абстракции.

2023-08-30 21:51 UTC, valentinsoe commented on internal/app/gophermart/middleware/auth/auth.go
> +			if userID == -1 {
Лучше не пользоваться magic numbers типа -1, а честно вернуть ошибку или булево значение ok

2023-08-30 21:51 UTC, valentinsoe commented on internal/app/gophermart/service/auth.go
> +	if user.ID == 0 {
Если не хочется иметь дело с ошибками, то в go есть принятый подход - возвращать булево значение для обозначения успеха операции.
Самый простой пример - получение значений из map

2023-08-30 21:51 UTC, valentinsoe commented on internal/model/accumulation.go
> +	OrderNumber      int        `json:"number,omitempty,string"`
Уже писал, но повторю - номер заказа не число. В нем может быть несколько десятков цифр.

2023-09-06 18:37 UTC, volnistii11 commented on cmd/gophermart/main.go
> +	err = database.RunMigrations(cfg.GetStorageDSN())
Библиотечка golang-migrate, которую я использовал, при создании миграцией, в качестве входных параметров принимает dsn

2023-09-06 19:05 UTC, volnistii11 commented on cmd/gophermart/main.go
> +
done

2023-09-06 19:24 UTC, volnistii11 commented on internal/app/gophermart/api/accumulation.go
> +		orderNumber, err = strconv.Atoi(string(body))
done

2023-09-06 19:31 UTC, volnistii11 commented on internal/app/gophermart/api/accumulation.go
> +		accumulation.UserID = r.Context().Value(model.ContextKeyUserID).(int)
done

2023-09-06 19:37 UTC, volnistii11 commented on internal/app/gophermart/api/accumulation.go
> +		w.Header().Add("content-type", "application/json")
done

2023-09-06 19:44 UTC, volnistii11 commented on internal/app/gophermart/api/auth.go
> +		jwtToken, err := a.authService.AuthenticateUser(&user, storage)
done

2023-09-06 20:03 UTC, volnistii11 commented on internal/app/gophermart/client/accrual.go
> +			for _, newOrder := range newOrders {
done

2023-09-06 20:36 UTC, volnistii11 commented on internal/app/gophermart/client/accrual.go
> +					logger.Error("", sl.Err(err))
done

2023-09-06 20:44 UTC, volnistii11 commented on internal/app/gophermart/middleware/auth/auth.go
> +			if userID == -1 {
done

2023-09-06 20:52 UTC, volnistii11 commented on internal/app/gophermart/service/auth.go
> +	if user.ID == 0 {
done

2023-09-06 21:47 UTC, volnistii11 commented on internal/app/gophermart/api/accumulation.go
> +		err = a.accumulationService.AddOrder(&accumulation, storage)
done

2023-09-06 22:07 UTC, volnistii11 commented on internal/app/gophermart/api/accumulation.go
> +		err := a.accumulationService.Withdraw(userID, &withdraw, storage)
done

2023-09-07 09:55 UTC, volnistii11 commented on internal/app/gophermart/service/accumulation.go
done

2023-09-08 03:50 UTC, valentinsoe approved these changes
Спасибо за исправления.
Написал ряд замечаний. Из них критично к исправлению только замечание про workgroup.
Принимаю работу, с верой в то, что одну строчку ты допишешь.

2023-09-08 03:50 UTC, valentinsoe commented on cmd/gophermart/main.go
> +		shutdownCtx, cancel := context.WithTimeout(serverCtx, 30*time.Second)
Исправлять не надо, но 30 секунд очень длинный таймаут.

2023-09-08 03:50 UTC, valentinsoe commented on internal/app/gophermart/client/accrual.go
> +						if errors.Is(err, cerrors.ErrHTTPStatusTooManyRequests) {
Сервис возвращает нам в заголовке Retry-After - сколько именно нам ждать.

2023-09-08 03:50 UTC, valentinsoe commented on internal/app/gophermart/client/accrual.go
> +			wg.Wait()
Нет ни одного вызова wg.Done() - значит здесь мы повиснем навсегда.
Единственная причина, почему тесты работают - они добавляют только 1 заказ и он сразу получает финальный статус.

2023-09-08 03:50 UTC, valentinsoe commented on internal/app/gophermart/client/accrual.go
> +				go func(newOrder string) {
При таком подходе у нас может быть запущено сколь угодно много горутин. Это не очень хорошая практика.
1) потребляет много памяти
2) с учетом того, что каждая горутина засыпает отдельно по 429 коду ошибки - будет "бомбить" внешний сервис большой пачкой запросов, "усыплять" сколько-то горутин и через минуту повторять.

2023-09-08 03:50 UTC, valentinsoe commented on internal/cerrors/cerrors.go
Название файла и пакета не самое удачное. Что значит "с" в начале?
Такие ошибки можно положить в константы(которыми они по сути и являются)

2023-09-08 03:50 UTC, valentinsoe commented on internal/repository/database/database.go
> +		if amount < accumulation.Amount {
Это в целом тоже бизнес-логика и есть бы лучше быть на уровень выше.
Как "аккуратно" вынести управление транзакциями из этого пакета - это интересная и полезная задача.
Рекомендую подумать сначала самому, а потом почитать статьи. Например вот такую: https://www.kaznacheev.me/posts/en/clean-transactions-in-hexagon/

2023-10-03 15:18 UTC, merged